# Generated by Django 2.1.7 on 2019-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
